tasks:
  default:
    - markdown
  dev:
    - watcher
  markdown: 'taskkit-docs'
  watcher: 'taskkit-watcher'

markdown:
  title: '{{title}}'
  files: '{{pages}}'

watcher:
  ignore:
    - '.git'
    - 'node_modules'
  files:
    '{{CWD}}/**/*.md':
      task: 'markdown'

